@@root_dir = File.expand_path(File.join(File.dirname(__FILE__),'..'))
@@build_lib_dir = File.expand_path(File.join(@@root_dir,'product','lib'))
require File.join(@@build_lib_dir,'string.rb')
require File.join(@@build_lib_dir,'filelist.rb')
require File.join(@@build_lib_dir,'msbuild.rb')
require File.join(@@build_lib_dir,'assemblyinfo.rb')
require File.join(@@build_lib_dir,'templatize.rb')
require File.join(@@build_lib_dir,'roundhouse.rb')
require File.join(@@build_lib_dir,'xunit.rb')
require File.join(@@build_lib_dir,'zipdirectory.rb')

require File.join(@@build_lib_dir,'testrunner.rb')
require File.join(@@build_lib_dir,'package.rb')
require File.join(@@build_lib_dir,'msdeploy.rb')